BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            text: ''
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
                on_press: handle_up()
            Button:
                text: 'Down'
                on_press: handle_down()
    Button:
        text: 'Convert'
        on_press: handle_convert()
    Label:
        id: output_km
